openapi: 3.0.0
info:
  description: ''
  version: '1.0.0'
  title: 'Prospects Full-Stack API'
  contact:
    email: 'igorovisk@gmail.com'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /v1/users:
    get:
      tags:
        - 'Users'
      summary: return all users.
      description: return all users.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref:
    post:
      tags:
        - 'Users'
      summary: return all users.
      description: return all users.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref:
